name: KlTheGuide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  expandable: ^4.1.4
  carousel_slider: ^2.2.1
  http: ^0.12.2
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.3
  timeline_list: ^0.0.5
  timeline_tile: ^1.0.0
  animated_splash_screen: ^1.0.1
  firebase_storage:
  firebase_database:
  flutter_email_sender: ^3.0.1
  dropdown_formfield: ^0.1.3
  firebase_admob: ^0.10.0+2
  flutter_platform_widgets: ^0.70.2
  pattern_formatter: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #ebook
    - assets/images/ebook/kltg-38.jpg
    - assets/images/ebook/kltg-37.jpg
    - assets/images/ebook/kltg-36.jpg
    - assets/images/ebook/kltg-35.jpg
    - assets/images/ebook/kltg-34.jpg
    - assets/images/ebook/kltg-33.jpg
    - assets/images/ebook/kltg-32.jpg
    - assets/images/ebook/kltg-31.jpg
    - assets/images/ebook/kltg-30.jpg
    - assets/images/ebook/kltg-29.jpg
    - assets/images/ebook/kltg-28.jpg
    - assets/images/ebook/kltg-27.jpg
    - assets/images/ebook/kltg-26.jpg
    - assets/images/ebook/kltg-25.jpg
    - assets/images/ebook/kltg-24.jpg
    - assets/images/ebook/kltg-23.jpg
    - assets/images/ebook/kltg-22.jpg
    - assets/images/ebook/kltg-21.jpg
    - assets/images/ebook/kltg-20.jpg
    - assets/images/ebook/kltg-19.jpg
    - assets/images/ebook/kltg-18.jpg
    - assets/images/ebook/kltg-17.jpg
    - assets/images/ebook/kltg-16.jpg
    - assets/images/ebook/kltg-15.jpg
    - assets/images/ebook/kltg-14.jpg
    - assets/images/ebook/kltg-13.jpg
    - assets/images/ebook/kltg-12.jpg
    - assets/images/ebook/kltg-11.jpg
    - assets/images/ebook/kltg-10.jpg
    - assets/images/ebook/kltg-9.jpg
    - assets/images/ebook/kltg-8.jpg
    - assets/images/ebook/kltg-7.jpg
    - assets/images/ebook/kltg-6.jpg
    - assets/images/ebook/kltg-5.jpg
    - assets/images/ebook/kltg-4.jpg
    - assets/images/ebook/kltg-3.jpg
    - assets/images/ebook/kltg-2.jpg
    - assets/images/ebook/kltg-1.jpg

  #client
    - assets/images/client/button-1.png
    - assets/images/client/button-2.png
    - assets/images/client/button-3.png
    - assets/images/client/button-4.png
    - assets/images/client/button-5.png
    - assets/images/client/century.png
    - assets/images/client/Garden-int-school.png
    - assets/images/client/global-link-properties.png
    - assets/images/client/hearing-partner.png
    - assets/images/client/hurix.png
    - assets/images/client/mesh.png
    - assets/images/client/star-avenue.png
    - assets/images/client/TAYLOR.png
    - assets/images/client/Thoneh-logo.png
    - assets/images/client/ubm.png
    - assets/images/client/univ-of-dundee.png
    - assets/images/client/WCT.png


  #travelTips
    - assets/images/TravelTips/breakdown.png  
    - assets/images/TravelTips/clothing.png  
    - assets/images/TravelTips/comfortable-wear.png  
    - assets/images/TravelTips/currency-code.png  
    - assets/images/TravelTips/emergency.png  
    - assets/images/TravelTips/hotel.png  
    - assets/images/TravelTips/timezone.png  
    - assets/images/TravelTips/visa-and-passports.png  
    - assets/images/TravelTips/weather.png  
    - assets/images/TravelTips/sunscreen.png 
    - assets/images/TravelTips/raingear.png 
    - assets/images/TravelTips/medicine.png 
    - assets/images/TravelTips/simcardanddiallingprefixes.png 
    - assets/images/TravelTips/dialling.png 
    - assets/images/TravelTips/wifi-wifi-rental.png

    


  #categories
    - assets/images/categories/Culture.jpg
    - assets/images/categories/Overview.jpg
    - assets/images/categories/Services.jpg
    - assets/images/categories/Sightseeing1.jpg
    - assets/images/categories/ThingsToDo.jpg
    - assets/images/categories/TravelTips1.jpg

  #subCatedgories
    - assets/images/subCatedgories/accomifation.jpg
    - assets/images/subCatedgories/around.jpg
    - assets/images/subCatedgories/food.jpg
    - assets/images/subCatedgories/games2.jpg
    - assets/images/subCatedgories/healthcare.jpg
    - assets/images/subCatedgories/historical.jpg
    - assets/images/subCatedgories/kids.JPG
    - assets/images/subCatedgories/music.jpg
    - assets/images/subCatedgories/nightlife.jpg
    - assets/images/subCatedgories/parks.jpg
    - assets/images/subCatedgories/shop.jpg
    - assets/images/subCatedgories/spa.jpg
    - assets/images/subCatedgories/Street.jpg
    - assets/images/subCatedgories/transport.jpg
    - assets/images/subCatedgories/whatToDo.jpg
    - assets/images/subCatedgories/dance.jpg
    - assets/images/subCatedgories/klatglance.jpg

  #placesToStay
    - assets/images/contentList/placesToStay/1.jpg
    - assets/images/contentList/placesToStay/2.jpg
    - assets/images/contentList/placesToStay/3.jpg
    - assets/images/contentList/placesToStay/4.jpg
    - assets/images/contentList/placesToStay/5.jpg    

  #historicalPlaces
    - assets/images/contentList/historicalPlaces/1.jpg
    - assets/images/contentList/historicalPlaces/2.jpg
    - assets/images/contentList/historicalPlaces/3.jpg
    - assets/images/contentList/historicalPlaces/4.jpg
    - assets/images/contentList/historicalPlaces/5.jpg

  #parks
    - assets/images/contentList/parks/1.jpg
    - assets/images/contentList/parks/2.jpg
    - assets/images/contentList/parks/3.jpg
    - assets/images/contentList/parks/4.jpg
    - assets/images/contentList/parks/5.jpg
    - assets/images/contentList/parks/6.jpg
    - assets/images/contentList/parks/7.jpg
    - assets/images/contentList/parks/8.jpg
    - assets/images/contentList/parks/9.jpg
    - assets/images/contentList/parks/10.jpg

  #music
    - assets/images/contentList/music/bangu.jpg
    - assets/images/contentList/music/erhu.jpg
    - assets/images/contentList/music/gambus.jpg
    - assets/images/contentList/music/gamelan.jpg
    - assets/images/contentList/music/Ghatam.jpg
    - assets/images/contentList/music/gong.jpg
    - assets/images/contentList/music/guqin.jpg
    - assets/images/contentList/music/kompang.jpg
    - assets/images/contentList/music/Miruthangam.jpg
    - assets/images/contentList/music/rebana-ubi.jpg
    - assets/images/contentList/music/serunai.jpg
    - assets/images/contentList/music/Sitar.jpg
    - assets/images/contentList/music/tabla.jpg
    - assets/images/contentList/music/tanggu.jpg
    - assets/images/contentList/music/veena.jpg
    

  #dance
    - assets/images/contentList/dance/Bhangra.jpg
    - assets/images/contentList/dance/Bharata_Natyam.jpg
    - assets/images/contentList/dance/Dikir_barat.jpg
    - assets/images/contentList/dance/joget.jpg
    - assets/images/contentList/dance/khattak.jpg
    - assets/images/contentList/dance/Lion-Dance.jpg
    - assets/images/contentList/dance/ngajat.jpg
    - assets/images/contentList/dance/odissi.jpg
    - assets/images/contentList/dance/sumazau.jpg
    - assets/images/contentList/dance/Zapin.jpg

    

  #malaysianGames

    - assets/images/contentList/malaysianGames/batu-seremban.jpg
    - assets/images/contentList/malaysianGames/congkak.jpg
    - assets/images/contentList/malaysianGames/top-spinning.jpg
    - assets/images/contentList/malaysianGames/wau.jpg
  
  
  #localFood
    - assets/images/contentList/localFood/1.jpg
    - assets/images/contentList/localFood/2.jpg
    - assets/images/contentList/localFood/3.jpg
    - assets/images/contentList/localFood/4.jpg
    - assets/images/contentList/localFood/5.jpg
  
  #relax
    - assets/images/contentList/relax/1.jpg
    - assets/images/contentList/relax/2.jpg
    - assets/images/contentList/relax/3.jpg
    - assets/images/contentList/relax/4.jpg
    - assets/images/contentList/relax/5.jpg
    - assets/images/contentList/relax/6.jpg
    - assets/images/contentList/relax/7.jpg
    - assets/images/contentList/relax/8.jpg
    - assets/images/contentList/relax/9.jpg
    - assets/images/contentList/relax/10.jpg 
  
  #klForKids
    - assets/images/contentList/klForKids/KLTowerMiniZoo.jpg
    - assets/images/contentList/klForKids/KLUpsideDownHouse.jpg
    - assets/images/contentList/klForKids/planetariumNEgara.jpg
    - assets/images/contentList/klForKids/PusatSainsNegara.jpg
  
  #whatToDoInKl
    - assets/images/contentList/whatToDoInKl/1.jpg 
    - assets/images/contentList/whatToDoInKl/2.jpg 
    - assets/images/contentList/whatToDoInKl/3.jpg 
    - assets/images/contentList/whatToDoInKl/4.jpg 
    - assets/images/contentList/whatToDoInKl/5.jpg  

  #whereToShop
    - assets/images/contentList/whereToShop/1.jpg 
    - assets/images/contentList/whereToShop/2.jpg 
    - assets/images/contentList/whereToShop/3.jpg 
    - assets/images/contentList/whereToShop/4.jpg 
    - assets/images/contentList/whereToShop/5.jpg  

  #nightLife
    - assets/images/contentList/nightLife/1.jpg 
    - assets/images/contentList/nightLife/2.jpg 
    - assets/images/contentList/nightLife/3.jpg 
    - assets/images/contentList/nightLife/4.jpg 

  #whereToEat
    - assets/images/contentList/whereToEat/1.jpg
    - assets/images/contentList/whereToEat/2.jpg 
    - assets/images/contentList/whereToEat/3.jpg 
    - assets/images/contentList/whereToEat/4.jpg  
  
  #medicalTourism
    - assets/images/contentList/medicalTourism/1.jpg
    - assets/images/contentList/medicalTourism/2.jpg 
    - assets/images/contentList/medicalTourism/3.jpg 
  
  #subMedicalTourism
    - assets/images/contentList/medicalTourism/sub-medical/Damai-Service-Hospital.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Dental-Pro.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Gleneagles-KL.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Imperial-Dental-Specialist-Centre.jpg
    - assets/images/contentList/medicalTourism/sub-medical/KLIDC.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Klinik-Dr-KO.jpg
    - assets/images/contentList/medicalTourism/sub-medical/KPJ-Tawakkal-KL.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Nexus-Clinic-KL.jpg
    - assets/images/contentList/medicalTourism/sub-medical/Peter-Chng.jpg    

  #transportaion
    - assets/images/contentList/transportaion/lrt.png
    - assets/images/contentList/transportaion/mrt.png
    - assets/images/contentList/transportaion/ktm-komuter.png
    - assets/images/contentList/transportaion/kl-monorail.png
    - assets/images/contentList/transportaion/rapid-kl-bus.png
    - assets/images/contentList/transportaion/go-kl-city-bus.png
    - assets/images/contentList/transportaion/kl-hop-on-hop-off.png
    - assets/images/contentList/transportaion/klia-express.png
    - assets/images/contentList/transportaion/bus.png
    - assets/images/contentList/transportaion/taxi.png
    - assets/images/contentList/transportaion/e-hailing-service.png

  #accomodation
    - assets/images/contentList/accomodation/1.jpg
    - assets/images/contentList/accomodation/2.jpg 
    - assets/images/contentList/accomodation/3.jpg 
    - assets/images/contentList/accomodation/4.jpg 
    - assets/images/contentList/accomodation/5.jpg 
    - assets/images/contentList/accomodation/6.jpg 
    - assets/images/contentList/accomodation/7.jpg 
    - assets/images/contentList/accomodation/8.jpg 
    - assets/images/contentList/accomodation/9.jpg 
    - assets/images/contentList/accomodation/10.jpg 
    
  #logo        
    - assets/images/Logo_100x50.png





    
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: RobotoCondens
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-light.ttf
          weight: 300    
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
